"""Endpoint and tool metadata for LingXing read-only MCP surfaces."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ToolArg:
    name: str
    arg_type: str
    required: bool = False
    description: str = ""
    default: Any = None

    def schema_property(self) -> dict[str, Any]:
        if self.arg_type == "integer":
            return {"type": "integer"}
        if self.arg_type == "boolean":
            return {"type": "boolean"}
        if self.arg_type == "array_string":
            return {"type": "array", "items": {"type": "string"}}
        if self.arg_type == "array_integer":
            return {"type": "array", "items": {"type": "integer"}}
        return {"type": "string"}


@dataclass(frozen=True)
class EndpointSpec:
    tool_name: str
    description: str
    endpoint: str
    category: str
    args: tuple[ToolArg, ...]
    pagination_mode: str = "offset"
    page_size: int = 1000
    data_path: str = "data"
    total_path: str | None = "total"
    next_token_path: str | None = "next_token"
    docs_path: str = ""
    body_defaults: tuple[tuple[str, Any], ...] = ()
    extra_headers: tuple[tuple[str, str], ...] = ()
    auto_profile: bool = False
    profile_type: str = "seller"
    result_kind: str = "rows"
    stable: bool = True
    search_field: str | None = None

    @property
    def input_schema(self) -> dict[str, Any]:
        properties = {arg.name: arg.schema_property() for arg in self.args}
        required = [arg.name for arg in self.args if arg.required]
        return {
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": False,
        }

    @property
    def defaults(self) -> dict[str, Any]:
        return {key: value for key, value in self.body_defaults}

    @property
    def headers(self) -> dict[str, str]:
        return {key: value for key, value in self.extra_headers}


def _s(name: str, *, required: bool = False, default: Any = None) -> ToolArg:
    return ToolArg(name=name, arg_type="string", required=required, default=default)


def _i(name: str, *, required: bool = False, default: Any = None) -> ToolArg:
    return ToolArg(name=name, arg_type="integer", required=required, default=default)


def _b(name: str, *, required: bool = False, default: Any = None) -> ToolArg:
    return ToolArg(name=name, arg_type="boolean", required=required, default=default)


def _as(name: str, *, required: bool = False, default: Any = None) -> ToolArg:
    return ToolArg(name=name, arg_type="array_string", required=required, default=default)


ADS_HEADERS = (("X-API-VERSION", "2"),)
AD_REPORT_ARGS = (_i("sid", required=True), _s("report_date", required=True), _i("profile_id"), _i("show_detail"))
AD_BASE_ARGS = (_i("sid", required=True), _i("profile_id"), _s("state"))
PROFIT_ARGS = (
    _i("sid", required=True),
    _s("start_date", required=True),
    _s("end_date", required=True),
    _s("currency_code"),
    _s("search_value"),
)
SOURCE_RANGE_ARGS = (
    _i("sid", required=True),
    _s("start_date", required=True),
    _s("end_date", required=True),
    _i("date_type"),
)
SOURCE_DATE_ARGS = (_i("sid", required=True), _s("event_date", required=True))
STOCK_ARGS = (_i("sid", required=True), _s("start_month", required=True), _s("end_month", required=True))
PRODUCT_PERFORMANCE_ARGS = (
    _i("sid", required=True),
    _s("start_date", required=True),
    _s("end_date", required=True),
    _s("search_field"),
    _as("search_value"),
    _s("summary_field"),
    _i("mid"),
    _s("currency_code"),
    _b("is_recently_enum"),
    _i("purchase_status"),
    _s("sort_field"),
    _s("sort_type"),
)


STABLE_ENDPOINT_SPECS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        tool_name="lingxing_ads_sp_campaign_report",
        description="SP 广告活动日报。",
        endpoint="/pb/openapi/newad/spCampaignReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spCampaignReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_product_ad_report",
        description="SP 广告商品日报，可直接按 ASIN 聚合。",
        endpoint="/pb/openapi/newad/spProductAdReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spProductAdReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_keyword_report",
        description="SP 关键词日报。",
        endpoint="/pb/openapi/newad/spKeywordReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spKeywordReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_target_report",
        description="SP 商品定位日报。",
        endpoint="/pb/openapi/newad/spTargetReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spTargetReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_search_term_report",
        description="SP 用户搜索词日报。",
        endpoint="/pb/openapi/newad/queryWordReports",
        category="ad_report",
        args=AD_REPORT_ARGS + (_s("target_type"),),
        docs_path="docs/newAd/report/queryWordReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1), ("target_type", "keyword")),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_campaign_report",
        description="SD 广告活动日报。",
        endpoint="/pb/openapi/newad/sdCampaignReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdCampaignReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_product_ad_report",
        description="SD 广告商品日报，可直接按 ASIN 聚合。",
        endpoint="/pb/openapi/newad/sdProductAdReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdProductAdReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_target_report",
        description="SD 商品定位日报。",
        endpoint="/pb/openapi/newad/sdTargetReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdTargetReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_campaign_report",
        description="SB 广告活动日报。",
        endpoint="/pb/openapi/newad/hsaCampaignReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/hsaCampaignReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_creative_report",
        description="SB 广告创意日报。",
        endpoint="/pb/openapi/newad/listHsaProductAdReport",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/listHsaProductAdReport.md",
        page_size=100,
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_purchased_asin_report",
        description="SB 已购买 ASIN 报表，用于按 ASIN 归因销售/订单。",
        endpoint="/pb/openapi/newad/hsaPurchasedAsinReports",
        category="ad_report",
        args=(_i("sid", required=True), _s("report_date", required=True), _i("profile_id")),
        docs_path="docs/newAd/report/hsaPurchasedAsinReports.md",
        page_size=100,
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_campaign_hourly",
        description="SP 广告活动小时数据。",
        endpoint="/pb/openapi/newad/spCampaignHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spCampaignHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_placement_hourly",
        description="SP 广告位小时数据。",
        endpoint="/pb/openapi/newad/spAdPlacementHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spAdPlacementHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_ad_group_hourly",
        description="SP 广告组小时数据。",
        endpoint="/pb/openapi/newad/spAdGroupHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spAdGroupHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_advertise_hourly",
        description="SP 广告小时数据。",
        endpoint="/pb/openapi/newad/spAdvertiseHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spAdvertiseHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_target_hourly",
        description="SP 投放小时数据。",
        endpoint="/pb/openapi/newad/spTargetHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spTargetHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_campaign_hourly",
        description="SB 广告活动小时数据。",
        endpoint="/pb/openapi/newad/sbCampaignHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sbCampaignHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_ad_group_hourly",
        description="SB 广告组小时数据。",
        endpoint="/pb/openapi/newad/sbAdGroupHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sbAdGroupHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_target_hourly",
        description="SB 投放小时数据。",
        endpoint="/pb/openapi/newad/sbTargetHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sbTargetHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_placement_hourly",
        description="SB 广告位小时数据。",
        endpoint="/pb/openapi/newad/sbAdPlacementHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sbAdPlacementHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_campaign_hourly",
        description="SD 广告活动小时数据。",
        endpoint="/pb/openapi/newad/sdCampaignHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdCampaignHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_ad_group_hourly",
        description="SD 广告组小时数据。",
        endpoint="/pb/openapi/newad/sdAdGroupHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdAdGroupHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_advertise_hourly",
        description="SD 广告小时数据。",
        endpoint="/pb/openapi/newad/sdAdvertiseHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdAdvertiseHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_target_hourly",
        description="SD 投放小时数据。",
        endpoint="/pb/openapi/newad/sdTargetHourData",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdTargetHourData.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_portfolios",
        description="广告组合列表。",
        endpoint="/pb/openapi/newad/portfolios",
        category="ad_base",
        args=(_i("sid", required=True), _i("profile_id")),
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/portfolios.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_campaigns",
        description="SP 广告活动基础数据。",
        endpoint="/pb/openapi/newad/spCampaigns",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/spCampaigns.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_ad_groups",
        description="SP 广告组基础数据。",
        endpoint="/pb/openapi/newad/spAdGroups",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/spAdGroups.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_product_ads",
        description="SP 广告商品基础数据。",
        endpoint="/pb/openapi/newad/spProductAds",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/spProductAds.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_keywords",
        description="SP 关键词基础数据。",
        endpoint="/pb/openapi/newad/spKeywords",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/spKeywords.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sp_targets",
        description="SP 商品定位基础数据。",
        endpoint="/pb/openapi/newad/spTargets",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/spTargets.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_campaigns",
        description="SD 广告活动基础数据。",
        endpoint="/pb/openapi/newad/sdCampaigns",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sdCampaigns.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_ad_groups",
        description="SD 广告组基础数据。",
        endpoint="/pb/openapi/newad/sdAdGroups",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sdAdGroups.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_product_ads",
        description="SD 广告商品基础数据。",
        endpoint="/pb/openapi/newad/sdProductAds",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sdProductAds.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sd_targets",
        description="SD 商品定位基础数据。",
        endpoint="/pb/openapi/newad/sdTargets",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sdTargets.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_campaigns",
        description="SB 广告活动基础数据。",
        endpoint="/pb/openapi/newad/hsaCampaigns",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/hsaCampaigns.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_ad_groups",
        description="SB 广告组基础数据。",
        endpoint="/pb/openapi/newad/hsaAdGroups",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/hsaAdGroups.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_creatives",
        description="SB 广告创意基础数据。",
        endpoint="/pb/openapi/newad/hsaProductAds",
        category="ad_base",
        args=(_i("sid", required=True), _i("profile_id")),
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sbAdHasProductAds.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_ads_sb_targets",
        description="SB 投放基础数据。",
        endpoint="/pb/openapi/newad/sbTargeting",
        category="ad_base",
        args=AD_BASE_ARGS,
        pagination_mode="next_token",
        page_size=100,
        docs_path="docs/newAd/baseData/sbTargeting.md",
        extra_headers=ADS_HEADERS,
        auto_profile=True,
    ),
    EndpointSpec(
        tool_name="lingxing_profit_seller",
        description="店铺维度利润统计。",
        endpoint="/bd/profit/statistics/open/seller/list",
        category="profit",
        args=PROFIT_ARGS + (_b("monthly_query"),),
        docs_path="docs/Statistics/statisticsOpenSeller.md",
        page_size=1000,
        data_path="data.records",
        total_path="data.total",
        result_kind="rows",
    ),
    EndpointSpec(
        tool_name="lingxing_profit_asin",
        description="ASIN 维度利润统计。",
        endpoint="/bd/profit/statistics/open/asin/list",
        category="profit",
        args=PROFIT_ARGS,
        docs_path="docs/Statistics/statisticsOpenASIN.md",
        page_size=1000,
        data_path="data.records",
        total_path="data.total",
        result_kind="rows",
        search_field="asin",
    ),
    EndpointSpec(
        tool_name="lingxing_profit_parent_asin",
        description="父 ASIN 维度利润统计。",
        endpoint="/bd/profit/statistics/open/parent/asin/list",
        category="profit",
        args=PROFIT_ARGS,
        docs_path="docs/Statistics/statisticsOpenParent.md",
        page_size=1000,
        data_path="data.records",
        total_path="data.total",
        result_kind="rows",
        search_field="parent_asin",
    ),
    EndpointSpec(
        tool_name="lingxing_product_performance",
        description="产品表现汇总，可按 ASIN / 父ASIN / MSKU 查询浏览、会话、广告和销量指标。",
        endpoint="/bd/productPerformance/openApi/asinList",
        category="source",
        args=PRODUCT_PERFORMANCE_ARGS,
        docs_path="docs/Statistics/AsinListNew.md",
        page_size=1000,
        data_path="data.list",
        total_path="data.total",
        body_defaults=(
            ("search_field", "asin"),
            ("summary_field", "asin"),
            ("sort_field", "volume"),
            ("sort_type", "desc"),
            ("is_recently_enum", False),
            ("purchase_status", 0),
        ),
    ),
    EndpointSpec(
        tool_name="lingxing_source_all_orders",
        description="亚马逊源表所有订单。",
        endpoint="/erp/sc/data/mws_report/allOrders",
        category="source",
        args=SOURCE_RANGE_ARGS,
        docs_path="docs/SourceData/AllOrders.md",
        page_size=1000,
    ),
    EndpointSpec(
        tool_name="lingxing_source_manage_inventory",
        description="亚马逊源表 FBA 库存。",
        endpoint="/erp/sc/data/mws_report/manageInventory",
        category="source",
        args=(_i("sid", required=True),),
        docs_path="docs/SourceData/ManageInventory.md",
        page_size=1000,
    ),
    EndpointSpec(
        tool_name="lingxing_source_daily_inventory",
        description="亚马逊源表每日库存。",
        endpoint="/erp/sc/data/mws_report/dailyInventory",
        category="source",
        args=SOURCE_DATE_ARGS,
        docs_path="docs/SourceData/DailyInventory.md",
        page_size=1000,
    ),
    EndpointSpec(
        tool_name="lingxing_source_reserved_inventory",
        description="亚马逊源表预留库存。",
        endpoint="/erp/sc/data/mws_report/reservedInventory",
        category="source",
        args=(_i("sid", required=True),),
        docs_path="docs/SourceData/ReservedInventory.md",
        page_size=1000,
    ),
    EndpointSpec(
        tool_name="lingxing_source_transaction",
        description="亚马逊源表交易明细。",
        endpoint="/erp/sc/data/mws_report/transaction",
        category="source",
        args=SOURCE_DATE_ARGS,
        docs_path="docs/SourceData/Transaction.md",
        page_size=1000,
    ),
    EndpointSpec(
        tool_name="lingxing_fba_stock_aggregate",
        description="FBA 库存新报表汇总。",
        endpoint="/cost/center/openApi/fba/gather/query",
        category="stock",
        args=STOCK_ARGS,
        docs_path="docs/Statistics/FbaStockAggregateListNew.md",
        page_size=200,
        data_path="data.row_data",
        total_path="data.total",
    ),
    EndpointSpec(
        tool_name="lingxing_fba_stock_detail",
        description="FBA 库存新报表明细。",
        endpoint="/cost/center/openApi/fba/detail/query",
        category="stock",
        args=STOCK_ARGS,
        docs_path="docs/Statistics/FbaStockDetailListNew.md",
        page_size=200,
        data_path="data.row_data",
        total_path="data.total",
    ),
    EndpointSpec(
        tool_name="lingxing_replenishment_summary",
        description="补货建议列表。",
        endpoint="/erp/sc/routing/restocking/analysis/getSummaryList",
        category="replenishment_summary",
        args=(_i("sid", required=True), _s("asin"), _i("mode")),
        docs_path="docs/FBASug/GetSummaryList.md",
        page_size=50,
        body_defaults=(("data_type", 1),),
    ),
    EndpointSpec(
        tool_name="lingxing_replenishment_asin_info",
        description="补货建议 ASIN 明细。",
        endpoint="/erp/sc/routing/fbaSug/asin/getInfo",
        category="replenishment_info",
        args=(_i("sid", required=True), _s("asin", required=True), _i("mode")),
        docs_path="docs/FBASug/InfoASIN.md",
        result_kind="object",
        pagination_mode="none",
    ),
)


EXPERIMENTAL_ENDPOINT_SPECS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        tool_name="lingxing_exp_ads_sp_placement_report",
        description="实验层：SP 广告位日报。",
        endpoint="/pb/openapi/newad/campaignPlacementReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/campaignPlacementReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sp_ad_group_report",
        description="实验层：SP 广告组日报。",
        endpoint="/pb/openapi/newad/spAdGroupReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/spAdGroupReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sp_purchased_asin_report",
        description="实验层：SP 已购买 ASIN 报表。",
        endpoint="/pb/openapi/newad/asinReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/asinReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sb_campaign_placement_report",
        description="实验层：SB 广告位日报。",
        endpoint="/pb/openapi/newad/hsaCampaignPlacementReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/hsaCampaignPlacementReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sb_ad_group_report",
        description="实验层：SB 广告组日报。",
        endpoint="/pb/openapi/newad/hsaAdGroupReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/hsaAdGroupReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sb_target_report",
        description="实验层：SB 投放日报。",
        endpoint="/pb/openapi/newad/listHsaTargetingReport",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/listHsaTargetingReport.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sb_search_term_report",
        description="实验层：SB 用户搜索词日报。",
        endpoint="/pb/openapi/newad/hsaQueryWordReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/hsaQueryWordReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sb_keyword_placement_report",
        description="实验层：SB 关键词广告位日报。",
        endpoint="/pb/openapi/newad/listHsaKeywordPlacementReport",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/listHsaKeywordPlacementReport.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sd_ad_group_report",
        description="实验层：SD 广告组日报。",
        endpoint="/pb/openapi/newad/sdAdGroupReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdAdGroupReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_sd_match_target_report",
        description="实验层：SD 匹配目标日报。",
        endpoint="/pb/openapi/newad/sdMatchTargetReports",
        category="ad_report",
        args=AD_REPORT_ARGS,
        docs_path="docs/newAd/report/sdMatchTargetReports.md",
        page_size=100,
        body_defaults=(("show_detail", 1),),
        extra_headers=ADS_HEADERS,
        auto_profile=True,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_ads_aba_report",
        description="实验层：ABA 搜索词周报下载信息。",
        endpoint="/pb/openapi/newad/abaReport",
        category="ad_report",
        args=(_s("country", required=True), _s("data_start_time", required=True)),
        docs_path="docs/newAd/reportDownload/abaReport.md",
        pagination_mode="none",
        result_kind="object",
        extra_headers=ADS_HEADERS,
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_finance_report_asin",
        description="实验层：结算利润报表 ASIN 视角。",
        endpoint="/bd/profit/report/open/report/asin/list",
        category="profit_report",
        args=PROFIT_ARGS + (_b("monthly_query"), _b("summary_enabled"), _s("order_status")),
        docs_path="docs/Finance/bdASIN.md",
        page_size=1000,
        data_path="data.records",
        total_path="data.total",
        search_field="asin",
        stable=False,
    ),
    EndpointSpec(
        tool_name="lingxing_exp_finance_report_seller",
        description="实验层：结算利润报表店铺视角。",
        endpoint="/bd/profit/report/open/report/seller/list",
        category="profit_report",
        args=(_i("sid", required=True), _s("start_date", required=True), _s("end_date", required=True), _s("currency_code"), _b("monthly_query"), _s("order_status")),
        docs_path="docs/Finance/bdSeller.md",
        page_size=1000,
        data_path="data.records",
        total_path="data.total",
        stable=False,
    ),
)


ALL_ENDPOINT_SPECS: tuple[EndpointSpec, ...] = STABLE_ENDPOINT_SPECS + EXPERIMENTAL_ENDPOINT_SPECS
ENDPOINT_SPECS_BY_NAME = {spec.tool_name: spec for spec in ALL_ENDPOINT_SPECS}
